### ISSUE TITLE
Add Info on SE Linux and Cockpit.

### ISSUE THREAD

**Issue by shaurya-007** [techlore/channel-content#10]
Since you guys have mentioned fedora, you should also mention SE Linux and Cockpit. Cockpit is a great tool to manage SE Linux and Firewalld graphically, besides it can also manage qemu/kvm vm's at almost no resource usage. Its meant for servers but works perfectly with desktops and laptops with almost no expenses in terms of resources (50 megs of ram at the most extreme). Besides cockpit is made by Red Hat.
https://cockpit-project.org/

**Comment by techlore-official** [comment]
https://github.com/techlore/channel-content/commit/51721ba868cfcad3cb9274932914a49869b20ae4 Added SELinux section. Will cover this more thoroughly in the video. Will consider referencing cockpit if there is time to cover it in the video!
