### ISSUE TITLE
Add Link to NSA Linux hardening Docs.

### ISSUE THREAD

**Issue by shaurya-007** [techlore/channel-content#11]
I made a little repo on Linux hardening Documents from the NSA (which is mostly on RHEL as apparently the NSA uses that stuff but these would work on almost any distro). There is some stuff from red hat about security and hardening in there too!
https://github.com/shaurya-007/NSA-Linux-Hardening-docs

**Comment by techlore-official** [comment]
Thanks for compiling this! Just added: https://github.com/techlore/channel-content/commit/d466e8dfdd7be667e683481c60134768082d52a3
