### ISSUE TITLE
Add Debian and Linux Mint to the Recommended Distros.

### ISSUE THREAD

**Issue by shaurya-007** [techlore/channel-content#12]
Debian is also recommended by PrivacyTools.io and is a very nice distro when it comes to Privacy/Security. Linux mint can be a nice alternative to ubuntu for new users as its UI is familiar and its history with privacy is really good (unlike ubuntu).

**Comment by techlore-official** [comment]
We actually recommend Debian on our site as well, just forgot to include it in the doc--will add it right away. We're not fans of Linux Mint personally, so we tend to stick with our 3 core recommendations. We'll be very clear in the video that almost any distro is fine, so Linux Mint is still very much welcome and we're supportive of that.
