### ISSUE TITLE
Add Info on community maintained enterprise Linux distros

### ISSUE THREAD

**Issue by shaurya-007** [techlore/channel-content#13]
I think you should add community enterprise linux distros like Rocky Linux as Enterprise kernels are much more maintained for security and you get features like SE Linux as well. Besides the Red Hat Security Bulletins also apply to Rocky Linux (as it is 1 on 1 binary compatible) and you get enterprise grade Security, but the downside would be older software, some of that can be fixed with flatpaks.

**Comment by techlore-official** [comment]
We're going to stick with our 3 core recommendations (Fedora, Debian, & Arch) just to simplify this issue. We could find dozens of distros to recommend for different reasons and this isn't the right video to dive into the pros/cons of each one. We're taking the approach of those 3 recommendations, but you can choose whichever distro you find works best for you and your use-case.
