### ISSUE TITLE
Add some Wise Advice

### ISSUE THREAD

**Issue by shaurya-007** [techlore/channel-content#20]
At the end, add the line "As we have mentioned before, Linux is Open Source, so the only limits are your time and effort in securing it. There is much more which can be done and there is no way we can cover all of that in one video so some rabbit-holes, you'll have to go down yourself if you're willing to." Or something along those lines.

**Comment by techlore-official** [comment]
This will probably be at the beginning or else the pitchforks will come chasing us quick!
