### ISSUE TITLE
Add Flatseal for sandboxing flatpaks.

### ISSUE THREAD

**Issue by shaurya-007** [techlore/channel-content#22]
Flatseal is a super easy GUI tool to sandbox flatpaks: https://flathub.org/apps/details/com.github.tchx84.Flatseal

**Comment by shaurya-007** [comment]
Its just a frontend fir built in flatpak settings and its one of the editors choice apps on flathub.

**Comment by techlore-official** [comment]
https://github.com/techlore/channel-content/pull/25 Done!
