### ISSUE TITLE
Firejail tor browser

### ISSUE THREAD

**Issue by 71Zombie** [techlore/channel-content#23]
Guide here: https://github.com/rusty-snake/firejailed-tor-browser

**Comment by techlore-official** [comment]
Good suggestion, but will be a bit too specific for this guide. We'll save this resource if we cover Tor more extensively in the future on Linux. This Linux Guide will cover firejail and tor individually though.

**Comment by oleanderxoxo** [comment]
It would be insecure: https://forums.whonix.org/t/tor-browser-hardening-hardened-malloc-firejail-apparmor-vs-web-fingerprint/7851/33
Firejail: https://github.com/netblue30/firejail/issues/3046
