### ISSUE TITLE
Context?

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [techlore/channel-content#29]
Hi!

In the show-notes, it's awesome that you link to your source.  Would you add context to those links, please, like a story title or something.  Many of the links do not contain a good description of what it talks about in the URI.

Thanks.

**Comment by henryistaken** [comment]
Thanks for the patience!

Since we transitioned SR over to be its own thing, it'll soon have its own unique repo that'll be managed by Nate instead of myself. I'll relay to him to try and implement something like this when the time comes.
