### ISSUE TITLE
iOS Guide cannot be openend.

### ISSUE THREAD

**Issue by TravelTrader** [techlore/channel-content#36]
Awesome work. I'm watching through your videos and I am trying to change everything step by step to privacy and security.

In your iOS video you mentioned and showed a PDF with every configuration on the iPhone (with menues, submenues, ...) but sadly the iOSGuide.pdf is not possible to open by different ways for me (iOS/Linux).

Any idea how to solve it?
Thank you very much.

**Comment by henryistaken** [comment]
It seems to be loading correctly on my end. If the GH embed isn't working properly, try directly downloading the file: 
<img width="1243" alt="Screen Shot 2022-10-14 at 10 10 09 AM" src="https://user-images.githubusercontent.com/64515030/195903644-6792b93e-32ca-4c82-aaef-06f58f5b8768.png">
