### ISSUE TITLE
The ULTIMATE Guide to Mastering NextDNS!

### ISSUE THREAD

**Issue by yokoffing** [techlore/channel-content#43]
**Source:** https://youtu.be/WUG57ynLb8I

Thank you for mentioning my NextDNS [guide](https://github.com/yokoffing/NextDNS-Config), @henry-fisher. Seeing the video on my feed made my week 🥹

Your video guide is great! I wanted to add a few notes that you may not be aware of:

- NextDNS recently [internalized](https://github.com/nextdns/metadata#readme) many of their lists. However, I have footnotes beside each category that links to the NextDNS Github repository where hosts their entries or blocklists. Where a category has been internalized, I provide the an older commit showing the list(s)/domains that were used.

- 14:46 Allow Affiliate & Tracking Links: For whatever reason, NextDNS is overly strict when this is disabled and breaks opening some email links. (I know from a security perspective that we shouldn't click email links, but the guide is for folks who don't want to deal with many inconveniences.) So it goes beyond Affiliate links.

- As recently as the end of May 2023, I did a lengthier [analysis](https://github.com/hagezi/dns-blocklists/discussions/1093) of the Hagezi lists and why **Light** is now recommended for most users.

TechLore Forum:
* [Question](https://discuss.techlore.tech/t/the-ultimate-guide-to-mastering-nextdns/4564/12) about iCloud Private Relay: I address that [here](https://github.com/yokoffing/NextDNS-Config#settings-gear); you have to disable the Block Page.

**Comment by henry-fisher** [comment]
Thanks for this! I'll paste this comment in the description + pinned comment so people can easily find it on YouTube. I just got back to the forum with your comment so they can see the iCloud Private Relay note 👌 Thanks for the kind words and thanks for the great guide!
