### ISSUE TITLE
Add sandboxing and AppArmor

### ISSUE THREAD

**Issue by Rohitrajak1807** [techlore/channel-content#9]
@techlore-official  we can use firejail to setup sandboxing for applications like our web browser. Additionally, apparmor can also be used to setup profiles for applications. Apparmor already comes with a lot of profiles which can be either downloaded as a separate package or is usually bundled with the main apparmor package.

**Comment by techlore-official** [comment]
Thanks for the note, would've been a nasty thing to miss, you'll find the commit here: https://github.com/techlore/channel-content/commit/c02e5392bf3a6b0136646a5ae1cbe1f06aac640a
